---
- name : Error type 1 with block and rescue
  hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Attempt and graceful roll back demo
      block:
        - name: Do Something
          ansible.builtin.shell: grep $(whoami) /etc/hosts

        - name: Force a failure, if previous one succeeds
          ansible.builtin.command: /bin/false
      rescue:
        - name: All is good if the first task failed
          when: ansible_failed_task.name == 'Do Something'
          ansible.builtin.debug:
            msg: All is good, ignore error as grep could not find 'me' in hosts

        - name: All is good if the second task failed
          when: "'/bin/false' in ansible_failed_result.cmd | d([])"
          ansible.builtin.fail:
            msg: It is still false!!!

